openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-aws-rds-mysql
components:
  schemas:
    variables:
      type: object
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default:
            publicly_accessible: false
          properties:
            domain_suffix:
              description: |
                Specify the domain suffix of the CloudMap. The domain suffix must be a valid DNS name.
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            kms_key_id:
              description: |
                Specify the KMS key ID which to encrypt the MySQL data. If not specified, the MySQL data will not be encrypted.
              title: Kms Key Id
              type: string
              x-walrus-ui:
                order: 2
            publicly_accessible:
              default: false
              description: |
                Specify whether to enable public access. If enabled, the MySQL service can be accessed from the public network.
              title: Publicly Accessible
              type: boolean
              x-walrus-ui:
                order: 4
            vpc_id:
              description: |
                Specify the ID of the VPC where the MySQL service applies. If not specified, a new VPC will be created.
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html.
          default: "8.0"
          enum:
          - "8.0"
          - "5.7"
          x-walrus-ui:
            group: Basic
            order: 5
        engine_parameters:
          title: Engine Parameters
          type: array
          description: |
            Specify the deployment engine parameters, select for https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.MySQL.Parameters.html.
          default: []
          items:
            properties:
              name:
                title: Name
                type: string
                x-walrus-ui:
                  order: 1
              value:
                title: Value
                type: string
                x-walrus-ui:
                  order: 2
            required:
            - name
            - value
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 6
        database:
          title: Database
          type: string
          description: "Specify the database name. The database name must be 2-64
            characters long and start with any lower letter, combined with number,
            or symbols: - _. \nThe database name cannot be MySQL forbidden keyword.\n"
          default: mydb
          minLength: 2
          maxLength: 64
          x-walrus-ui:
            group: Basic
            order: 9
        username:
          title: Username
          type: string
          description: |
            Specify the account username. The username must be 2-16 characters long and start with lower letter, combined with number, or symbol: _.
            The username cannot be MySQL forbidden keyword.
            See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.KnownIssuesAndLimitations.html#MySQL.Concepts.KnownIssuesAndLimitations.KillProcedures.
          default: rdsuser
          minLength: 2
          maxLength: 16
          x-walrus-ui:
            group: Basic
            order: 7
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 8-32 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
            See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints.
          format: password
          writeOnly: true
          minLength: 8
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 8
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            class: db.t3.medium
          properties:
            class:
              default: db.t3.medium
              description: |
                Specify the computing resources. See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Summary.
              title: Class
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 10
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          default:
            class: gp2
            size: 20480
          properties:
            class:
              default: gp2
              description: |
                Specify the storage class. See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html.
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              default: 20480
              description: |
                Specify the storage size. Unit is megabyte.
              minimum: 20480
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 11
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
